# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3f53bde0ee414ec896701006fa05e2042764a5a18ccec5c1f368cc07cfb1a4421c6bdcaf4f7accc8f5ee54d880e50d12cf46e461d76a3b9f76b5bd47132765

test:
  secret_key_base: 48c50d8a118fd190a7791ad5cd122c3b1012fe18c4ba12fb0d832e97ef32d414835197e9f6c4ccd2e688dbf2856fa35baa015e620ed344aa260a479701829747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
